[debug] [2020-02-17T18:17:01.489Z] ----------------------------------------------------------------------
[debug] [2020-02-17T18:17:01.492Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve --only functions
[debug] [2020-02-17T18:17:01.492Z] CLI Version:   7.13.0
[debug] [2020-02-17T18:17:01.492Z] Platform:      win32
[debug] [2020-02-17T18:17:01.492Z] Node Version:  v13.7.0
[debug] [2020-02-17T18:17:01.494Z] Time:          Mon Feb 17 2020 19:17:01 GMT+0100 (MitteleuropÃ¤ische Normalzeit)
[debug] [2020-02-17T18:17:01.494Z] ----------------------------------------------------------------------
[debug] [2020-02-17T18:17:01.494Z] 
[debug] [2020-02-17T18:17:01.503Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2020-02-17T18:17:01.503Z] > authorizing via signed-in user
[debug] [2020-02-17T18:17:01.504Z] [iam] checking project o-cheese-us for permissions ["firebase.projects.get"]
[debug] [2020-02-17T18:17:01.506Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/o-cheese-us:testIamPermissions  

[debug] [2020-02-17T18:17:02.407Z] <<< HTTP RESPONSE 200
[debug] [2020-02-17T18:17:02.411Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/o-cheese-us  
 
[debug] [2020-02-17T18:17:02.662Z] <<< HTTP RESPONSE 200
[debug] [2020-02-17T18:17:02.670Z] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.join (path.js:375:7)
    at Object.<anonymous> (C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:21:39)
    at Generator.next (<anonymous>)
    at C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:4:12)
    at Object.start (C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\functions.js:19:16)
    at C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:25:40
    at arrayMap (C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\lodash\lodash.js:639:23)
    at Function.map (C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\lodash\lodash.js:9554:14)
    at C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:24:29
    at Generator.next (<anonymous>)
    at C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Buntspecht\AppData\Roaming\npm\node_modules\firebase-tools\lib\serve\index.js:4:12)
[error] 
[error] Error: An unexpected error has occurred.
